name: GitHub CLI Extensions Test
on:
  workflow_dispatch:
jobs:
  GitHub_CLI_Extensions_Test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: gh extension install vilmibm/gh-user-status
      - run: gh user-status get seanh
