name: Cookiecutter
on:
  workflow_dispatch:
jobs:
  Cookiecutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install tox
      - run: tox -e template
      - run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ secrets.PAT }}
